// Datový číselník – katalog všech dostupných položek v nabídce
export const katalog = [
    // Jídla
    {
        typ: "jidlo",
        nazev: "Smažený sýr",
        zakladniCena: 85,
        cenaKrabice: 15,
        jeVegeVolba: false,
    },
    {
        typ: "jidlo",
        nazev: "Kuřecí burger",
        zakladniCena: 120,
        cenaKrabice: 20,
        jeVegeVolba: true,
    },
    {
        typ: "jidlo",
        nazev: "Hranolky",
        zakladniCena: 45,
        cenaKrabice: 15,
        jeVegeVolba: false,
    },
    {
        typ: "jidlo",
        nazev: "Pizza Margherita",
        zakladniCena: 130,
        cenaKrabice: 25,
        jeVegeVolba: false,
    },
    {
        typ: "jidlo",
        nazev: "Kebab v lavašu",
        zakladniCena: 110,
        cenaKrabice: 20,
        jeVegeVolba: true,
    },
    {
        typ: "jidlo",
        nazev: "Párek v rohlíku",
        zakladniCena: 40,
        cenaKrabice: 15,
        jeVegeVolba: false,
    },
    {
        typ: "jidlo",
        nazev: "Caesar salát",
        zakladniCena: 95,
        cenaKrabice: 20,
        jeVegeVolba: true,
    },
    {
        typ: "jidlo",
        nazev: "Svíčková na smetaně",
        zakladniCena: 155,
        cenaKrabice: 25,
        jeVegeVolba: false,
    },
    {
        typ: "jidlo",
        nazev: "Onion rings",
        zakladniCena: 55,
        cenaKrabice: 15,
        jeVegeVolba: false,
    },
    {
        typ: "jidlo",
        nazev: "Wrap s tuňákem",
        zakladniCena: 100,
        cenaKrabice: 20,
        jeVegeVolba: false,
    },
    // Nápoje
    {
        typ: "napoj",
        nazev: "Kofola 0.5l",
        zakladniCena: 35,
        zalohaZaLahev: 3,
        jeAlkohol: false,
    },
    {
        typ: "napoj",
        nazev: "Pivo Kozel 0.5l",
        zakladniCena: 45,
        zalohaZaLahev: 3,
        jeAlkohol: true,
    },
    {
        typ: "napoj",
        nazev: "Voda 0.75l",
        zakladniCena: 25,
        zalohaZaLahev: 3,
        jeAlkohol: false,
    },
    {
        typ: "napoj",
        nazev: "Coca-Cola 0.33l",
        zakladniCena: 30,
        zalohaZaLahev: 3,
        jeAlkohol: false,
    },
    {
        typ: "napoj",
        nazev: "Sprite 0.33l",
        zakladniCena: 30,
        zalohaZaLahev: 3,
        jeAlkohol: false,
    },
    {
        typ: "napoj",
        nazev: "Pivo Pilsner Urquell 0.5l",
        zakladniCena: 55,
        zalohaZaLahev: 3,
        jeAlkohol: true,
    },
    {
        typ: "napoj",
        nazev: "Džus pomeranč 0.25l",
        zakladniCena: 28,
        zalohaZaLahev: 3,
        jeAlkohol: false,
    },
];